package brelaz;

import java.util.LinkedList;

public class Test {

	public static void main(String[] args) throws Exception {

		Channel C0 = new Channel("C0");
		Channel C1 = new Channel("C1");
		Channel C2 = new Channel("C2");
		Channel C3 = new Channel("C3");
		Channel C4 = new Channel("C4");
		LinkedList<Channel> channelsList = new LinkedList<Channel>();
		channelsList.add(C0);
		channelsList.add(C1);
		channelsList.add(C2);
		channelsList.add(C3);
		channelsList.add(C4);
		Network network = new Network(channelsList);
		Device A = new Device("A");
		Device B = new Device("B");
		Device C = new Device("C");
		Device D = new Device("D");
		Device E = new Device("E");
		Device F = new Device("F");
		Device G = new Device("G");
		Device H = new Device("H");
		Device I = new Device("I");
		Device J = new Device("J");
		Device K = new Device("K");
		Device L = new Device("L");
		Device M = new Device("M");
		Device N = new Device("N");
		Arch AB = new Arch(A, B);
		Arch BC = new Arch(B, C);
		Arch BD = new Arch(B, D);
		Arch CD = new Arch(C, D);
		Arch ED = new Arch(E, D);
		Arch JD = new Arch(J, D);
		Arch FD = new Arch(F, D);
		Arch FG = new Arch(G, F);
		Arch FI = new Arch(I, F);
		Arch FH = new Arch(F, H);
		Arch GH = new Arch(G, H);
		Arch IK = new Arch(I, K);
		Arch IN = new Arch(I, N);
		Arch HN = new Arch(H, N);
		Arch HL = new Arch(H, L);
		Arch LM = new Arch(L, M);
		A.addArch(AB);
		B.addArch(AB);
		B.addArch(BC);
		B.addArch(BD);
		C.addArch(BC);
		C.addArch(CD);
		D.addArch(FD);
		D.addArch(BD);
		D.addArch(ED);
		D.addArch(JD);
		D.addArch(CD);
		E.addArch(ED);
		F.addArch(FD);
		F.addArch(FI);
		F.addArch(FH);
		F.addArch(FG);
		G.addArch(FG);
		G.addArch(GH);
		H.addArch(GH);
		H.addArch(FH);
		H.addArch(HL);
		H.addArch(HN);
		I.addArch(FI);
		I.addArch(IK);
		I.addArch(IN);
		J.addArch(JD);
		K.addArch(IK);
		L.addArch(HL);
		L.addArch(LM);
		M.addArch(LM);
		Graph graph = new Graph(network);
		graph.addNode(A);
		graph.addNode(B);
		graph.addNode(C);
		graph.addNode(D);
		graph.addNode(E);
		graph.addNode(F);
		graph.addNode(G);
		graph.addNode(H);
		graph.addNode(I);
		graph.addNode(J);
		graph.addNode(K);
		graph.addNode(L);
		graph.addNode(M);
		graph.addNode(N);
		graph.printGraph();
		BrelazAlgorithm brelazAlgorithm = new BrelazAlgorithm(graph);
		brelazAlgorithm.startAlgorithm();
		graph.printGraph();

	}
}
