package brelaz;

public class Test {

	public static void main(String[] args) throws Exception {

		Channel S = new Channel("S");
		Channel T = new Channel("T");
		// Channels H = new Channels("H");
		// Channels O = new Channels("O");
		// Channels P = new Channels("P");
		Network N = new Network();
		N.addChannel(S);
		N.addChannel(T);
		// N.addChan(H);
		// N.addChan(O);
		// N.addChan(P);
		Device A = new Device("A");
		Device B = new Device("B");
		Device C = new Device("C");
		Device E = new Device("E");
		Device F = new Device("F");
		Device D = new Device("D");
		Arch AB = new Arch(A, B);
		Arch AF = new Arch(A, F);
		Arch BC = new Arch(C, B);
		Arch CD = new Arch(C, D);
		Arch DF = new Arch(D, F);
		Arch DE = new Arch(D, E);
		Arch EF = new Arch(E, F);
		Arch DB = new Arch(B, D);
		A.addArch(AB);
		A.addArch(AF);
		B.addArch(AB);
		B.addArch(BC);
		B.addArch(DB);
		C.addArch(CD);
		C.addArch(BC);
		D.addArch(DE);
		D.addArch(DF);
		D.addArch(CD);
		D.addArch(DB);
		E.addArch(EF);
		E.addArch(DE);
		F.addArch(AF);
		F.addArch(EF);
		F.addArch(DF);
		A.addChannel(S);
		A.addChannel(T);
		// A.addChan(H);
		// A.addChan(O);
		// A.addChan(P);
		B.addChannel(S);
		B.addChannel(T);
		// B.addChan(H);
		// B.addChan(O);
		// B.addChan(P);
		C.addChannel(S);
		C.addChannel(T);
		// C.addChan(H);
		// C.addChan(O);
		// C.addChan(P);
		D.addChannel(S);
		D.addChannel(T);
		// D.addChan(H);
		// D.addChan(O);
		// D.addChan(P);
		E.addChannel(S);
		E.addChannel(T);
		// E.addChan(H);
		// E.addChan(O);
		// E.addChan(P);
		F.addChannel(S);
		F.addChannel(T);
		// F.addChan(H);
		// F.addChan(O);
		// F.addChan(P);
		Graph Gr = new Graph();
		Gr.addNode(A);
		Gr.addNode(B);
		Gr.addNode(C);
		Gr.addNode(D);
		Gr.addNode(E);
		Gr.addNode(F);
		Gr.printGraph();
		BrelazAlgorithm Bre = new BrelazAlgorithm(Gr, N);
		Bre.startAlgorithm();
		Gr.printGraph();

	}
}
